<?php

// Block this page if the administrator is not logged in.
session_start();
if(!isset($_SESSION["admin_id"]))
{
	header("location:admin_login.php");
	exit();
}

include("dataconnection.php");
require_once("admin_shell.php");
require_once("product_catalog_helpers.php");

// Use one session token for every product record change.
if(empty($_SESSION["admin_catalog_csrf"]))
{
	$_SESSION["admin_catalog_csrf"] = bin2hex(random_bytes(32));
}
$csrf_token = $_SESSION["admin_catalog_csrf"];

// Escape database values before displaying them in the administrator page.
function admin_product_html($value)
{
	return htmlspecialchars((string)$value,ENT_QUOTES,"UTF-8");
}

// Store one result message and redirect to prevent duplicate form submissions.
function admin_product_redirect($type,$message,$location="admin_product.php")
{
	$_SESSION["admin_product_flash"] = array("type"=>$type,"message"=>$message);
	header("Location: ".$location,true,303);
	exit();
}

// Only remove image files generated by this page; bundled menu images are preserved.
function admin_product_remove_generated_image($stored_path)
{
	$normalised = str_replace("\\","/",trim((string)$stored_path));
	if(preg_match("#^image/product-[a-z0-9-]+-[a-f0-9]{16}\\.(?:jpg|png|webp)$#",$normalised)!==1)
	{
		return;
	}

	$absolute_path = __DIR__.DIRECTORY_SEPARATOR.str_replace("/",DIRECTORY_SEPARATOR,$normalised);
	$image_directory = realpath(__DIR__.DIRECTORY_SEPARATOR."image");
	$file_directory = realpath(dirname($absolute_path));
	if($image_directory!==false && $file_directory===$image_directory && is_file($absolute_path))
	{
		unlink($absolute_path);
	}
}

// Validate a real image upload and return its safe project-relative path.
function admin_product_store_upload($file,$product_id,$required)
{
	if(!is_array($file) || !isset($file["error"]) || (int)$file["error"]===UPLOAD_ERR_NO_FILE)
	{
		if($required)
		{
			throw new RuntimeException("Please choose a product image.");
		}
		return null;
	}

	if((int)$file["error"]!==UPLOAD_ERR_OK)
	{
		throw new RuntimeException("The product image could not be uploaded.");
	}
	if((int)$file["size"]<=0 || (int)$file["size"]>5*1024*1024)
	{
		throw new RuntimeException("The product image must be 5 MB or smaller.");
	}
	if(!is_uploaded_file($file["tmp_name"]))
	{
		throw new RuntimeException("The uploaded image is invalid.");
	}

	$allowed_extensions = array("jpg","jpeg","png","webp");
	$extension = strtolower(pathinfo((string)$file["name"],PATHINFO_EXTENSION));
	if(!in_array($extension,$allowed_extensions,true))
	{
		throw new RuntimeException("Only JPG, PNG or WebP product images are allowed.");
	}

	$finfo = finfo_open(FILEINFO_MIME_TYPE);
	$mime_type = $finfo ? finfo_file($finfo,$file["tmp_name"]) : false;
	if($finfo)
	{
		finfo_close($finfo);
	}
	$mime_extensions = array("image/jpeg"=>"jpg","image/png"=>"png","image/webp"=>"webp");
	if($mime_type===false || !isset($mime_extensions[$mime_type]))
	{
		throw new RuntimeException("The selected file is not a supported image.");
	}

	$image_size = getimagesize($file["tmp_name"]);
	if($image_size===false || $image_size[0]<100 || $image_size[1]<100 || $image_size[0]>6000 || $image_size[1]>6000)
	{
		throw new RuntimeException("The product image dimensions must be between 100 and 6000 pixels.");
	}

	$image_directory = __DIR__.DIRECTORY_SEPARATOR."image";
	if(!is_dir($image_directory) || !is_writable($image_directory))
	{
		throw new RuntimeException("The image folder is not available for uploads.");
	}

	$safe_id = strtolower(preg_replace("/[^A-Za-z0-9]+/","-",$product_id));
	$safe_id = trim($safe_id,"-");
	if($safe_id==="")
	{
		$safe_id = "item";
	}
	$filename = "product-".$safe_id."-".bin2hex(random_bytes(8)).".".$mime_extensions[$mime_type];
	$absolute_path = $image_directory.DIRECTORY_SEPARATOR.$filename;
	if(!move_uploaded_file($file["tmp_name"],$absolute_path))
	{
		throw new RuntimeException("The product image could not be saved.");
	}

	return "image/".$filename;
}

// Process product changes only through validated POST requests.
if($_SERVER["REQUEST_METHOD"]==="POST")
{
	$submitted_token = (string)($_POST["csrf_token"] ?? "");
	if(!hash_equals($csrf_token,$submitted_token))
	{
		admin_product_redirect("error","The request expired. Please try again.");
	}

	$action = (string)($_POST["action"] ?? "");
	if($action==="save_product")
	{
		$mode = (string)($_POST["mode"] ?? "add");
		$product_id = strtoupper(trim((string)($_POST["product_id"] ?? "")));
		$product_name = trim((string)($_POST["product_name"] ?? ""));
		$product_desc = trim((string)($_POST["product_desc"] ?? ""));
		$product_category = trim((string)($_POST["product_category"] ?? ""));
		$product_price = filter_var($_POST["product_price"] ?? null,FILTER_VALIDATE_FLOAT);
		$product_stock = filter_var($_POST["product_stock"] ?? null,FILTER_VALIDATE_INT,array("options"=>array("min_range"=>0,"max_range"=>9999)));
		$product_status = trim((string)($_POST["product_status"] ?? ""));

		if(!in_array($mode,array("add","update"),true) || preg_match("/^[A-Z0-9]{1,5}$/",$product_id)!==1)
		{
			admin_product_redirect("error","Please enter a valid product ID using up to 5 letters or numbers.");
		}
		if($product_name==="" || strlen($product_name)>100 || $product_desc==="" || strlen($product_desc)>255)
		{
			admin_product_redirect("error","Please complete the product name and description within their character limits.");
		}
		if($product_price===false || $product_price<0.01 || $product_price>999.99 || $product_stock===false)
		{
			admin_product_redirect("error","Please enter a valid price and stock quantity.");
		}
		if(!in_array($product_status,array("Active","Inactive","Out of Stock"),true))
		{
			admin_product_redirect("error","Please select a valid product status.");
		}

		$category_stmt = mysqli_prepare($connect,"SELECT category_name FROM category WHERE category_name=? AND category_isDelete=0 LIMIT 1");
		if(!$category_stmt)
		{
			admin_product_redirect("error","The selected category could not be checked.");
		}
		mysqli_stmt_bind_param($category_stmt,"s",$product_category);
		mysqli_stmt_execute($category_stmt);
		$category_result = mysqli_stmt_get_result($category_stmt);
		$category_exists = mysqli_fetch_assoc($category_result)!==null;
		mysqli_stmt_close($category_stmt);
		if(!$category_exists)
		{
			admin_product_redirect("error","Please select an available category.");
		}

		$old_image = "";
		$uploaded_image = null;
		$transaction_started = false;
		try
		{
			if($mode==="update")
			{
				$current_stmt = mysqli_prepare($connect,"SELECT product_image FROM product WHERE product_id=? AND product_isDelete=0 LIMIT 1");
				if(!$current_stmt)
				{
					throw new RuntimeException("The product could not be loaded.");
				}
				mysqli_stmt_bind_param($current_stmt,"s",$product_id);
				mysqli_stmt_execute($current_stmt);
				$current_result = mysqli_stmt_get_result($current_stmt);
				$current_product = mysqli_fetch_assoc($current_result) ?: null;
				mysqli_stmt_close($current_stmt);
				if(!$current_product)
				{
					throw new RuntimeException("The selected product is unavailable.");
				}
				$old_image = (string)$current_product["product_image"];
			}

			$uploaded_image = admin_product_store_upload($_FILES["product_image"] ?? null,$product_id,$mode==="add");
			$product_image = $uploaded_image ?? $old_image;
			mysqli_begin_transaction($connect);
			$transaction_started = true;

			if($mode==="add")
			{
				$save_stmt = mysqli_prepare($connect,"INSERT INTO product(product_id,product_name,product_desc,product_image,product_category,product_price,product_stock,product_status,product_isDelete) VALUES(?,?,?,?,?,?,?,?,0)");
				if(!$save_stmt)
				{
					throw new RuntimeException("The product could not be prepared.");
				}
				mysqli_stmt_bind_param($save_stmt,"sssssdis",$product_id,$product_name,$product_desc,$product_image,$product_category,$product_price,$product_stock,$product_status);
			}
			else
			{
				$save_stmt = mysqli_prepare($connect,"UPDATE product SET product_name=?,product_desc=?,product_image=?,product_category=?,product_price=?,product_stock=?,product_status=? WHERE product_id=? AND product_isDelete=0");
				if(!$save_stmt)
				{
					throw new RuntimeException("The product could not be prepared.");
				}
				mysqli_stmt_bind_param($save_stmt,"ssssdiss",$product_name,$product_desc,$product_image,$product_category,$product_price,$product_stock,$product_status,$product_id);
			}

			if(!mysqli_stmt_execute($save_stmt))
			{
				throw new RuntimeException($mode==="add" ? "The product ID already exists." : "The product could not be updated.");
			}
			mysqli_stmt_close($save_stmt);
			mysqli_commit($connect);
			$transaction_started = false;

			if($uploaded_image!==null && $old_image!=="" && $old_image!==$uploaded_image)
			{
				admin_product_remove_generated_image($old_image);
			}
			admin_product_redirect("success",$mode==="add" ? "Product added successfully." : "Product updated successfully.");
		}
		catch(Throwable $error)
		{
			if($transaction_started)
			{
				mysqli_rollback($connect);
			}
			if($uploaded_image!==null)
			{
				admin_product_remove_generated_image($uploaded_image);
			}
			admin_product_redirect("error",$error->getMessage());
		}
	}

	if($action==="delete_product")
	{
		$product_id = strtoupper(trim((string)($_POST["product_id"] ?? "")));
		if(preg_match("/^[A-Z0-9]{1,5}$/",$product_id)!==1)
		{
			admin_product_redirect("error","Please select a valid product.");
		}

		mysqli_begin_transaction($connect);
		try
		{
			$image_stmt = mysqli_prepare($connect,"SELECT product_image FROM product WHERE product_id=? AND product_isDelete=0 FOR UPDATE");
			if(!$image_stmt)
			{
				throw new RuntimeException("The product could not be locked.");
			}
			mysqli_stmt_bind_param($image_stmt,"s",$product_id);
			mysqli_stmt_execute($image_stmt);
			$image_result = mysqli_stmt_get_result($image_stmt);
			$product_row = mysqli_fetch_assoc($image_result) ?: null;
			mysqli_stmt_close($image_stmt);
			if(!$product_row)
			{
				throw new RuntimeException("The selected product is unavailable.");
			}

			$delete_stmt = mysqli_prepare($connect,"UPDATE product SET product_isDelete=1,product_status='Inactive' WHERE product_id=? AND product_isDelete=0");
			if(!$delete_stmt)
			{
				throw new RuntimeException("The product could not be prepared for removal.");
			}
			mysqli_stmt_bind_param($delete_stmt,"s",$product_id);
			if(!mysqli_stmt_execute($delete_stmt) || mysqli_stmt_affected_rows($delete_stmt)!==1)
			{
				throw new RuntimeException("The selected product is unavailable.");
			}
			mysqli_stmt_close($delete_stmt);

			// Rewards linked to a removed product must no longer be redeemable.
			$reward_stmt = mysqli_prepare($connect,"UPDATE reward SET reward_status='Inactive' WHERE reward_product=? AND reward_isDelete=0");
			if(!$reward_stmt)
			{
				throw new RuntimeException("Linked rewards could not be updated.");
			}
			mysqli_stmt_bind_param($reward_stmt,"s",$product_id);
			if(!mysqli_stmt_execute($reward_stmt))
			{
				throw new RuntimeException("Linked rewards could not be updated.");
			}
			mysqli_stmt_close($reward_stmt);
			mysqli_commit($connect);
			// Keep the uploaded image while the record is soft-deleted so the
			// recycle bin can restore a complete product instead of a broken photo.
			admin_product_redirect("success","Product removed successfully.");
		}
		catch(Throwable $error)
		{
			mysqli_rollback($connect);
			admin_product_redirect("error",$error->getMessage());
		}
	}

	admin_product_redirect("error","The requested product action is not supported.");
}

$flash = $_SESSION["admin_product_flash"] ?? null;
unset($_SESSION["admin_product_flash"]);

// Load active categories for both the filter and product editor.
$categories = array();
$category_result = mysqli_query($connect,"SELECT category_id,category_name FROM category WHERE category_isDelete=0 ORDER BY category_name");
if($category_result)
{
	while($category_row = mysqli_fetch_assoc($category_result))
	{
		$categories[] = $category_row;
	}
}

$search = trim((string)($_GET["search"] ?? ""));
$category_filter = trim((string)($_GET["category"] ?? ""));
$status_filter = trim((string)($_GET["status"] ?? ""));
$stock_filter = trim((string)($_GET["stock"] ?? ""));
if(!in_array($status_filter,array("","Active","Inactive","Out of Stock"),true))
{
	$status_filter = "";
}
if(!in_array($stock_filter,array("","in_stock","out_of_stock"),true))
{
	$stock_filter = "";
}

// Apply all product filters in one prepared query.
$like_search = "%".$search."%";
$product_stmt = mysqli_prepare($connect,
	"SELECT product_id,product_name,product_desc,product_image,product_category,product_price,product_stock,product_status
	 FROM product
	 WHERE product_isDelete=0
	 AND (?='' OR product_id LIKE ? OR product_name LIKE ? OR product_desc LIKE ?)
	 AND (?='' OR product_category=?)
	 AND (?='' OR product_status=?)
	 AND (?='' OR (?='in_stock' AND product_stock>0) OR (?='out_of_stock' AND product_stock<=0))
	 ORDER BY product_name");
$products = array();
if($product_stmt)
{
	mysqli_stmt_bind_param($product_stmt,"sssssssssss",$search,$like_search,$like_search,$like_search,$category_filter,$category_filter,$status_filter,$status_filter,$stock_filter,$stock_filter,$stock_filter);
	mysqli_stmt_execute($product_stmt);
	$product_result = mysqli_stmt_get_result($product_stmt);
	while($product_row = mysqli_fetch_assoc($product_result))
	{
		$products[] = $product_row;
	}
	mysqli_stmt_close($product_stmt);
}

// Load the selected product into the editor without trusting query-string values.
$editing_product = null;
$edit_id = strtoupper(trim((string)($_GET["edit"] ?? "")));
if($edit_id!=="")
{
	$edit_stmt = mysqli_prepare($connect,"SELECT product_id,product_name,product_desc,product_image,product_category,product_price,product_stock,product_status FROM product WHERE product_id=? AND product_isDelete=0 LIMIT 1");
	if($edit_stmt)
	{
		mysqli_stmt_bind_param($edit_stmt,"s",$edit_id);
		mysqli_stmt_execute($edit_stmt);
		$edit_result = mysqli_stmt_get_result($edit_stmt);
		$editing_product = mysqli_fetch_assoc($edit_result) ?: null;
		mysqli_stmt_close($edit_stmt);
	}
}

// Keep CSV output aligned with the current Product search and filters.
$product_export_params = array("type"=>"products");
if($search!=="") $product_export_params["search"] = $search;
if($category_filter!=="") $product_export_params["category"] = $category_filter;
if($status_filter!=="") $product_export_params["status"] = $status_filter;
if($stock_filter!=="") $product_export_params["stock"] = $stock_filter;
$product_export_url = "admin_export.php?".http_build_query($product_export_params);
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Manage Products - EasyOrder</title>
	<link rel="stylesheet" href="style.css">
	<link rel="stylesheet" href="admin_style.css">
</head>
<body class="admin-body">
<?php easyorder_admin_shell_start("admin_product.php"); ?>

	<!-- Product management heading and current database scope. -->
	<section class="admin-page-heading">
		<div>
			<p class="admin-eyebrow">CATALOG MANAGEMENT</p>
			<h1>Products</h1>
			<p>Search, update and publish menu products with their customer-facing images.</p>
			<p class="admin-print-context">Filters: Search <?php echo admin_product_html($search!=="" ? $search : "All"); ?> · Category <?php echo admin_product_html($category_filter!=="" ? $category_filter : "All"); ?> · Status <?php echo admin_product_html($status_filter!=="" ? $status_filter : "All"); ?> · Stock <?php echo admin_product_html($stock_filter!=="" ? str_replace("_"," ",$stock_filter) : "All"); ?></p>
		</div>
		<!-- Export and print only the current filtered catalogue result. -->
		<div class="admin-output-actions">
			<a class="admin-secondary-link" href="<?php echo admin_product_html($product_export_url); ?>">Export CSV</a>
			<button type="button" class="admin-secondary-button" onclick="window.print()">Print List</button>
			<a class="admin-primary-link" href="#product-editor">Add Product</a>
		</div>
	</section>

	<?php if($flash): ?>
		<div class="admin-alert admin-alert-<?php echo admin_product_html($flash["type"]); ?>" role="status">
			<?php echo admin_product_html($flash["message"]); ?>
		</div>
	<?php endif; ?>

	<!-- Product search and availability filters. -->
	<section class="admin-catalog-filter-panel">
		<form class="admin-catalog-filter-form" method="get" action="admin_product.php">
			<label class="admin-catalog-search">
				<span>Search products</span>
				<input type="search" name="search" value="<?php echo admin_product_html($search); ?>" placeholder="Product ID, name or description">
			</label>
			<label>
				<span>Category</span>
				<select name="category">
					<option value="">All categories</option>
					<?php foreach($categories as $category): ?>
						<option value="<?php echo admin_product_html($category["category_name"]); ?>"<?php echo $category_filter===$category["category_name"] ? " selected" : ""; ?>><?php echo admin_product_html($category["category_name"]); ?></option>
					<?php endforeach; ?>
				</select>
			</label>
			<label>
				<span>Status</span>
				<select name="status">
					<option value="">All statuses</option>
					<option value="Active"<?php echo $status_filter==="Active" ? " selected" : ""; ?>>Active</option>
					<option value="Inactive"<?php echo $status_filter==="Inactive" ? " selected" : ""; ?>>Inactive</option>
					<option value="Out of Stock"<?php echo $status_filter==="Out of Stock" ? " selected" : ""; ?>>Out of Stock</option>
				</select>
			</label>
			<label>
				<span>Stock</span>
				<select name="stock">
					<option value="">All stock levels</option>
					<option value="in_stock"<?php echo $stock_filter==="in_stock" ? " selected" : ""; ?>>In stock</option>
					<option value="out_of_stock"<?php echo $stock_filter==="out_of_stock" ? " selected" : ""; ?>>Out of stock</option>
				</select>
			</label>
			<div class="admin-catalog-filter-actions">
				<button type="submit">Apply Filters</button>
				<a href="admin_product.php">Reset</a>
			</div>
		</form>
	</section>

	<!-- Filtered product results from the live database. -->
	<section class="admin-catalog-results">
		<header class="admin-section-heading">
			<div>
				<p class="admin-eyebrow">PRODUCT LIST</p>
				<h2>Menu products</h2>
			</div>
			<span class="admin-catalog-result-meta"><?php echo count($products); ?> result<?php echo count($products)===1 ? "" : "s"; ?></span>
		</header>
		<div class="admin-catalog-table-wrap">
			<table class="admin-catalog-table">
				<thead>
					<tr><th>Image</th><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th class="admin-print-hide">Actions</th></tr>
				</thead>
				<tbody>
				<?php if(!$products): ?>
					<tr><td class="admin-catalog-empty" colspan="7">No products match the selected filters.</td></tr>
				<?php else: ?>
					<?php foreach($products as $product): ?>
						<tr>
							<td><img class="admin-product-thumbnail" src="<?php echo admin_product_html(catalog_product_image($product["product_image"])); ?>" alt=""></td>
							<td><strong><?php echo admin_product_html($product["product_name"]); ?></strong><small><?php echo admin_product_html($product["product_id"]); ?></small></td>
							<td><?php echo admin_product_html($product["product_category"]); ?></td>
							<td>RM <?php echo number_format((float)$product["product_price"],2); ?></td>
							<td><?php echo (int)$product["product_stock"]; ?></td>
							<td><span class="admin-status-badge <?php echo $product["product_status"]==="Active" && (int)$product["product_stock"]>0 ? "status-success" : ($product["product_status"]==="Out of Stock" || (int)$product["product_stock"]<=0 ? "status-warning" : "status-danger"); ?>"><?php echo admin_product_html($product["product_status"]); ?></span></td>
							<td class="admin-print-hide">
								<div class="admin-catalog-row-actions">
									<a href="admin_product.php?edit=<?php echo rawurlencode($product["product_id"]); ?>#product-editor">Edit</a>
									<form method="post" action="admin_product.php" onsubmit="return confirm('Remove this product from the menu?');">
										<input type="hidden" name="csrf_token" value="<?php echo admin_product_html($csrf_token); ?>">
										<input type="hidden" name="action" value="delete_product">
										<input type="hidden" name="product_id" value="<?php echo admin_product_html($product["product_id"]); ?>">
										<button type="submit">Remove</button>
									</form>
								</div>
							</td>
						</tr>
					<?php endforeach; ?>
				<?php endif; ?>
				</tbody>
			</table>
		</div>
	</section>

	<!-- Add or edit one product and its customer-facing image. -->
	<section id="product-editor" class="admin-catalog-editor">
		<header class="admin-section-heading">
			<div>
				<p class="admin-eyebrow"><?php echo $editing_product ? "UPDATE PRODUCT" : "NEW PRODUCT"; ?></p>
				<h2><?php echo $editing_product ? "Edit ".admin_product_html($editing_product["product_name"]) : "Add a menu product"; ?></h2>
			</div>
			<?php if($editing_product): ?><a class="admin-secondary-link" href="admin_product.php#product-editor">Cancel Edit</a><?php endif; ?>
		</header>

		<form class="admin-catalog-editor-form" name="productfrm" method="post" action="admin_product.php" enctype="multipart/form-data" data-product-form>
			<input type="hidden" name="csrf_token" value="<?php echo admin_product_html($csrf_token); ?>">
			<input type="hidden" name="action" value="save_product">
			<input type="hidden" name="mode" value="<?php echo $editing_product ? "update" : "add"; ?>">

			<div class="admin-product-image-editor">
				<img class="admin-product-preview" data-image-preview src="<?php echo admin_product_html($editing_product ? catalog_product_image($editing_product["product_image"]) : "image/logo.png"); ?>" alt="Product image preview">
				<label>
					<span><?php echo $editing_product ? "Replace product image" : "Product image"; ?></span>
					<input type="file" name="product_image" accept="image/jpeg,image/png,image/webp"<?php echo $editing_product ? "" : " required"; ?> data-image-input>
				</label>
				<p>JPG, PNG or WebP. Maximum 5 MB. The full image is shown on customer pages.</p>
			</div>

			<div class="admin-catalog-fields">
				<label class="admin-form-field">
					<span>Product ID</span>
					<input type="text" name="product_id" maxlength="5" pattern="[A-Za-z0-9]{1,5}" value="<?php echo admin_product_html($editing_product["product_id"] ?? ""); ?>"<?php echo $editing_product ? " readonly" : ""; ?> required>
				</label>
				<label class="admin-form-field">
					<span>Product name</span>
					<input type="text" name="product_name" maxlength="100" value="<?php echo admin_product_html($editing_product["product_name"] ?? ""); ?>" required>
				</label>
				<label class="admin-form-field admin-field-wide">
					<span>Description</span>
					<textarea name="product_desc" maxlength="255" rows="3" required><?php echo admin_product_html($editing_product["product_desc"] ?? ""); ?></textarea>
				</label>
				<label class="admin-form-field">
					<span>Category</span>
					<select name="product_category" required>
						<option value="">Select a category</option>
						<?php foreach($categories as $category): ?>
							<option value="<?php echo admin_product_html($category["category_name"]); ?>"<?php echo ($editing_product["product_category"] ?? "")===$category["category_name"] ? " selected" : ""; ?>><?php echo admin_product_html($category["category_name"]); ?></option>
						<?php endforeach; ?>
					</select>
				</label>
				<label class="admin-form-field">
					<span>Price (RM)</span>
					<input type="number" name="product_price" min="0.01" max="999.99" step="0.01" value="<?php echo admin_product_html($editing_product["product_price"] ?? ""); ?>" required>
				</label>
				<label class="admin-form-field">
					<span>Stock quantity</span>
					<input type="number" name="product_stock" min="0" max="9999" step="1" value="<?php echo admin_product_html($editing_product["product_stock"] ?? "0"); ?>" required>
				</label>
				<label class="admin-form-field">
					<span>Status</span>
					<select name="product_status" required>
						<?php $selected_status = $editing_product["product_status"] ?? "Active"; ?>
						<option value="Active"<?php echo $selected_status==="Active" ? " selected" : ""; ?>>Active</option>
						<option value="Inactive"<?php echo $selected_status==="Inactive" ? " selected" : ""; ?>>Inactive</option>
						<option value="Out of Stock"<?php echo $selected_status==="Out of Stock" ? " selected" : ""; ?>>Out of Stock</option>
					</select>
				</label>
			</div>

			<div class="admin-catalog-form-actions">
				<button type="submit"><?php echo $editing_product ? "Save Product Changes" : "Add Product"; ?></button>
				<?php if($editing_product): ?><a href="admin_product.php#product-editor">Cancel</a><?php endif; ?>
			</div>
		</form>
	</section>

<?php easyorder_admin_shell_end(); ?>

<script>
// Preview a selected local image and reject oversized files before submission.
const productImageInput = document.querySelector("[data-image-input]");
const productImagePreview = document.querySelector("[data-image-preview]");
if(productImageInput && productImagePreview)
{
	productImageInput.addEventListener("change",function()
	{
		const selectedFile = this.files && this.files[0] ? this.files[0] : null;
		if(!selectedFile)
		{
			return;
		}
		const acceptedTypes = ["image/jpeg","image/png","image/webp"];
		if(selectedFile.size>5*1024*1024 || !acceptedTypes.includes(selectedFile.type))
		{
			alert("Please choose a JPG, PNG or WebP image no larger than 5 MB.");
			this.value = "";
			return;
		}
		productImagePreview.src = URL.createObjectURL(selectedFile);
	});
}
</script>
</body>
</html>
